# Generated by Django 5.1.1 on 2024-09-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
